### ISSUE TITLE
[bug] KeyError: 'bias_correct'

### ISSUE THREAD

**Issue by neuronflow** [BrainLesion/eReg#53]
throws error:
```
(brainles2) (base) florian@a4000-21an1:~/flow/BrainLesion/preprocessing$ /home/florian/miniconda3/envs/brainles2/bin/python /home/florian/flow/BrainLesion/preprocessing/ereg_tests/try_ereg.py
Traceback (most recent call last):
  File "/home/florian/flow/BrainLesion/preprocessing/ereg_tests/try_ereg.py", line 11, in <module>
    registration_obj.register(
  File "/home/florian/miniconda3/envs/brainles2/lib/python3.10/site-packages/ereg/registration.py", line 153, in register
    if self.parameters["bias_correct"]:
KeyError: 'bias_correct'
```
reproducible example:
```
t1c = "/home/florian/flow/BrainLesion/preprocessing/example/example_data/OtherEXampleFromTCIA/MRHR_T1_AX_POST_GAD_OtherEXampleTCIA_TCGA-FG-6692_Si_TCGA-FG-6692_MRHR_T1_AX_POST_GAD_SE_13_se2d1r_t1c.nii.gz"

fla = "/home/florian/flow/BrainLesion/preprocessing/example/example_data/OtherEXampleFromTCIA/MRHR_FLAIR_AX_OtherEXampleTCIA_TCGA-FG-6692_Si_TCGA-FG-6692_MRHR_FLAIR_AX_SE_IR_5_tir2d1_21_fla.nii.gz"


from ereg.registration import RegistrationClass

registration_obj = (
    RegistrationClass()
)  # the configuration file to use to customize the registration, and is optional
registration_obj.register(
    target_image=t1c,  # the target image, which can be either a file or SimpleITK.Image object
    moving_image=fla,  # the moving image, which can be either a file or SimpleITK.Image object
    output_image="/home/florian/flow/BrainLesion/preprocessing/ereg_tests/warped.nii.gz",  # the output image to save the registered image to
    transform_file="/home/florian/flow/BrainLesion/preprocessing/ereg_tests/transform.mat",  # the transform file to save the transform to; if already present, will use this transform instead of computing a new one
    log_file="/home/florian/flow/BrainLesion/preprocessing/ereg_tests/log.log",  # the log file to write to
)

```

**Comment by neuronflow** [comment]
that also seems to be blocking here:
https://github.com/BrainLesion/preprocessing/pull/49

**Comment by neuronflow** [comment]
I am using this example data for my tests:
https://github.com/BrainLesion/preprocessing/tree/main/example/example_data

**Comment by neuronflow** [comment]
hmm now I get:
```
(brainles2) (base) florian@a4000-21an1:~/flow/BrainLesion/preprocessing$ /home/florian/miniconda3/envs/brainles2/bin/python /home/florian/flow/BrainLesion/preprocessing/ereg_tests/try_ereg.py
Traceback (most recent call last):
  File "/home/florian/flow/BrainLesion/preprocessing/ereg_tests/try_ereg.py", line 11, in <module>
    registration_obj.register(
  File "/home/florian/miniconda3/envs/brainles2/lib/python3.10/site-packages/ereg/registration.py", line 174, in register
    self.transform = self._register_image_and_get_transform(
  File "/home/florian/miniconda3/envs/brainles2/lib/python3.10/site-packages/ereg/registration.py", line 392, in _register_image_and_get_transform
    metric = self.parameters["metric"].lower()
KeyError: 'metric'
```


we need unit tests to avoid breaking things:
https://github.com/BrainLesion/eReg/issues/52

**Comment by neuronflow** [comment]
https://github.com/BrainLesion/eReg/issues/56
